namespace bettinggame.data.Entities
{
    public enum Country
    {
        Egypt,
        Morocco,
        Nigeria,
        Senegal,
        Tunisia,
        Australia,
        Iran,
        Japan,
        KoreaRepublic,
        SaudiArabia,
        Belgium,
        Croatia,
        Denmark,
        England,
        France,
        Germany,
        Iceland,
        Poland,
        Portugal,
        Russia,
        Serbia,
        Spain,
        Sweden,
        Switzerland,
        CostaRica,
        Mexico,
        Panama,
        Argentina,
        Brazil,
        Colombia,
        Peru,
        Uruguay    
    }
}
